title: "Arian Designs"
description: "My portfolio website"
baseurl: "" # Leave empty if deploying to root
url: "https://ariantechzone-stack.github.io" # Replace with your GitHub username
theme: minima
