title: "Arian Designs"
description: "Clean, modern, and professional design portfolio by Arian."
url: "https://ariantechzone-stack.github.io"
baseurl: ""

author: "Arian"

social:
  name: Arian Designs
  links:
    - https://instagram.com/_arian.designs_
    - https://pinterest.com/ariantech
    - https://github.com/ariantechzone-stack
    - https://www.fiverr.com/r_kumar101/modern-instagram-posts-and-social-media-graphics
    - https://linkedin.com/in/https://www.linkedin.com/in/arian-varx-0660b539b/
